name: Deploy

on:
  push:
    branches:
      - master  # Ensure this matches the deploy condition

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Node
        uses: actions/setup-node@v3  # Updated version
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Updated version
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Matches the push branch

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Updated version
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use default token
          publish_dir: ./build
